{{ if .Values.webdav.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webdav
spec:
  type: {{ default "ClusterIP" .Values.webdav.serviceType }}
  selector:
    app: webdav
  ports:
    - port: {{ .Values.webdav.servicePort }}
      targetPort: {{ .Values.webdav.port }}
{{ end }}
