{{ if .Values.webdav.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: webdav
  annotations:
{{- if .Values.webdav.annotations }}
{{- .Values.webdav.annotations | toYaml | nindent 4 }}
{{- end }}
data:
{{ end }}
