{{ if .Values.sftp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sftp-secret
  annotations:
{{- if .Values.sftp.annotations }}
{{- .Values.sftp.annotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
{{- if .Values.sftp.hostKey }}
  ssh_host_ed25519_key: {{ .Values.sftp.hostKey.ed25519 | b64enc }}
  ssh_host_rsa_key: {{ .Values.sftp.hostKey.rsa | b64enc }}
{{- end }}
{{ end }}
