{{ if .Values.sftp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  annotations:
{{- if .Values.sftp.annotations }}
{{- .Values.sftp.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: sftp
  replicas: {{ .Values.sftp.replicas }}
  template:
    metadata:
      labels:
        app: sftp
    spec:
      schedulerName: {{ .Values.scheduler }}
      serviceAccount: lamp
{{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: lamp-image-pull-secrets
{{- end }}
      containers:
        - name: sftp
          image: {{ .Values.sftp.image }}
          imagePullPolicy: Always
          command:
            - sh
            - /sftp-configmap/entrypoint.sh
          ports:
            - containerPort: {{ .Values.sftp.port }}
{{- if .Values.sftp.livenessProbe }}
          livenessProbe:
{{ .Values.sftp.livenessProbe | toYaml | indent 12 }}
{{- end }}
          resources:
{{- if .Values.sftp.resources }}
{{ .Values.sftp.resources | toYaml | indent 12 }}
{{- end }}
          env:
            - name: SFTP_USERS
              value: "{{ .Values.sftp.username }}:{{ required "Please provide sftp.password" .Values.sftp.password }}"
          volumeMounts:
            - mountPath: /home/{{ .Values.sftp.username }}
              name: lamp-data
            - mountPath: /sftp-configmap
              name: sftp-configmap
      volumes:
        - name: lamp-data
          persistentVolumeClaim: { claimName: lamp-data }
        - name: sftp-configmap
          configMap: { name: sftp }

{{ end }}
