{{ if .Values.sftp.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: sftp
  annotations:
{{- if .Values.sftp.annotations }}
{{- .Values.sftp.annotations | toYaml | nindent 4 }}
{{- end }}
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e

{{- if .Values.sftp.config.enabled }}
    echo "Copying verbose config into place"
    cp /sftp-configmap/sshd_config_verbose_logging /etc/ssh/sshd_config
{{- end }}

    exec /entrypoint

  sshd_config_verbose_logging: |
    # Secure defaults
    # See: https://stribika.github.io/2015/01/04/secure-secure-shell.html
    Protocol 2
    HostKey /etc/ssh/ssh_host_ed25519_key
    HostKey /etc/ssh/ssh_host_rsa_key

    # Faster connection
    # See: https://github.com/atmoz/sftp/issues/11
    UseDNS no

    # Limited access
    PermitRootLogin no
    X11Forwarding no
    AllowTcpForwarding no

    # Force sftp and chroot jail
    Subsystem sftp internal-sftp
    ForceCommand internal-sftp
    ChrootDirectory %h

{{- if .Values.sftp.verbose }}
    # Enable this for more logs
    LogLevel VERBOSE
{{- end }}

{{ end }}
