lamp:
  image: php:7.3-apache

database:
  image: mysql:5
  rootPassword: rootpw
  userName: lamp
  userPassword: changeme
  tinyConfiguration: ""
  memcacheKnownEnabled: false
  persistence:
    storageClass: ""

persistence:
  storageClass: ""

ingress:
  host: ~
  hosts: []
  tls:
    enabled: false
    certManager:
      clusterIssuer: ""
      issuer: ""
  modsecurity:
    enabled: false
    owasp: false
    whitelist: ""
    adminWhitelist: ""