lamp:
  image: php:7.3-apache
  replicas: 1
  ingressUrl: ""
  startupScript: ""
  annotations: ~
  ingressAnnotations: ~

database:
  enabled: false
  image: mysql:5
  rootPassword: rootpw
  userName: lamp
  userPassword: changeme
  tinyConfiguration: ""
  persistence:
    storageClass: ""
  annotations: ~
  secretAnnotations: ~

persistence:
  storageClass: ""

ingress:
  hosts: []
  tls:
    enabled: false
    certManager:
      clusterIssuer: ""
      issuer: ""
  modsecurity:
    enabled: false
    owasp: false
    whitelist: ""
    restrictedUris: []
    restrictedWhitelist: ""
  nginx:
    configurationSnippet: ""

sftp:
  enabled: false
  serviceType: LoadBalancer
  servicePort: 1022
  image: atmoz/sftp:alpine
  port: 22
  livenessProbe: ~
  username: sftp-user
  password: ~
  hostKey:
    # ssh-keygen -t ed25519 -f ssh_host_ed25519_key < /dev/null
    #ed25519: ~
    # ssh-keygen -t rsa -b 4096 -f ssh_host_rsa_key < /dev/null
    #rsa: ~
  config:
    enabled: false
    verbose: false
  annotations: ~

webdav:
  enabled: false
  serviceType: ClusterIP
  servicePort: 80
  username: webdav-user
  password: ~
  image: wheatstalk/docker-php-webdav:0.2
  port: 80
  annotations: ~
  ingress:
    hosts: []
    tls:
      enabled: false
      certManager:
        clusterIssuer: ""
        issuer: ""
    modsecurity:
      enabled: false
      owasp: false
      whitelist: ""
      restrictedUris: []
      restrictedWhitelist: ""
    nginx:
      configurationSnippet: ""
