lamp:
  image: php:7.3-apache
  replicas: 1
  ingressUrl: ""
  startupScript: ""

database:
  enabled: false
  image: mysql:5
  rootPassword: rootpw
  userName: lamp
  userPassword: changeme
  tinyConfiguration: ""
  persistence:
    storageClass: ""

persistence:
  storageClass: ""

ingress:
  hosts: []
  tls:
    enabled: false
    certManager:
      clusterIssuer: ""
      issuer: ""
  modsecurity:
    enabled: false
    owasp: false
    whitelist: ""
    restrictedUris: []
    restrictedWhitelist: ""
  nginx:
    configurationSnippet: ""

sftp:
  enabled: false
  serviceType: LoadBalancer
  servicePort: 1022
  image: atmoz/sftp:alpine
  port: 22
  livenessProbe: ~
  username: sftp-user
  password: ~
  config:
    enabled: false
    verbose: false
