lamp:
  image: php:7.3-apache
  replicas: 1
  ingressUrl: ""

database:
  enabled: false
  image: mysql:5
  rootPassword: rootpw
  userName: lamp
  userPassword: changeme
  tinyConfiguration: ""
  memcacheKnownEnabled: false
  persistence:
    storageClass: ""

persistence:
  storageClass: ""

ingress:
  hosts: []
  tls:
    enabled: false
    certManager:
      clusterIssuer: ""
      issuer: ""
  modsecurity:
    enabled: false
    owasp: false
    whitelist: ""
    restrictedUris: []
    restrictedWhitelist: ""
  nginx:
    configurationSnippet: ""
