apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamp-data
  annotations:
    "helm.sh/resource-policy": keep
{{- if .Values.lamp.annotations }}
{{- .Values.lamp.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  {{- $storageClass := default .Values.persistence.storageClass .Values.lamp.persistence.storageClass }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 16Gi
