apiVersion: v1
kind: Service
metadata:
  name: lamp
  annotations:
{{- if .Values.lamp.annotations }}
{{- .Values.lamp.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  selector:
    app: lamp
  ports:
    - port: 80
      targetPort: 80
