{{- if (or .Values.ingress.host .Values.ingress.hosts) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lamp
  annotations:
{{- if .Values.ingress.tls.certManager.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManager.clusterIssuer }}
{{- end }}
{{- if .Values.ingress.tls.certManager.issuer }}
    cert-manager.io/issuer: {{ .Values.ingress.tls.certManager.issuer }}
{{- end }}
{{- if .Values.ingress.modsecurity.enabled }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
{{- if .Values.ingress.modsecurity.owasp }}
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
{{- end }}
{{- if .Values.ingress.modsecurity.whitelist }}
      SecRule REMOTE_ADDR "!@ipMatch {{ .Values.ingress.modsecurity.whitelist }}" "id:10000,deny"
{{- end }}
{{- if .Values.ingress.modsecurity.adminWhitelist }}
      SecRule REQUEST_URI "@beginsWith /admin" "id:10010,chain,deny"
      SecRule REMOTE_ADDR "!@ipMatch {{ .Values.ingress.modsecurity.adminWhitelist }}"
{{- end }}
{{- end }}
{{- if (and .Values.ingress.modsecurity.enabled .Values.ingress.modsecurity.whitelist ) }}
    lamp-memcached/ingress.modsecurity.whitelist: {{ .Values.ingress.modsecurity.whitelist | quote }}
{{- end }}
{{- if (and .Values.ingress.modsecurity.enabled .Values.ingress.modsecurity.adminWhitelist ) }}
    lamp-memcached/ingress.modsecurity.adminWhitelist: {{ .Values.ingress.modsecurity.adminWhitelist | quote }}
{{- end }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: /
          backend:
            serviceName: lamp
            servicePort: 80
{{- end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
{{- if .Values.ingress.host }}
      - {{ .Values.ingress.host }}
{{- end }}
{{- range .Values.ingress.hosts }}
      - {{ . }}
{{- end }}
      secretName: lamp-cert
{{- end }}
{{- end }}