{{ if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  annotations:
{{- if .Values.database.annotations }}
{{- .Values.database.annotations | toYaml | nindent 4 }}
{{- end }}
{{- if .Values.database.secretAnnotations }}
{{- .Values.database.secretAnnotations | toYaml | nindent 4 }}
{{- end }}
type: Opaque
data:
  root-password: "{{ .Values.database.rootPassword | b64enc }}"
  user-name: "{{ .Values.database.userName | b64enc }}"
  user-password: "{{ .Values.database.userPassword | b64enc }}"
{{ end }}
