{{ if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
{{- if .Values.database.annotations }}
{{- .Values.database.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
{{ end }}
